# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-message-enter-patch

# >> macros
BuildArch: noarch
# << macros

Summary:    A patch to send messages using the enter key for the jolla-messages app.
Version:    0.0.1
Release:    1
Group:      Qt/Qt
License:    TODO
Source0:    %{name}-%{version}.tar.bz2
Requires:   patchmanager

%description
A patch to send messages using the enter key for the jolla-messages app.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/patchmanager/patches/sailfishos-message-enter-patch
cp -r patch/* %{buildroot}/usr/share/patchmanager/patches/sailfishos-message-enter-patch
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager/patches/sailfishos-message-enter-patch
# >> files
# << files
