# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-message-enter-patch

# >> macros
BuildArch: noarch
# << macros

Summary:    A patch to send messages using the enter key for the jolla-messages app.
Version:    0.0.2
Release:    1
Group:      Qt/Qt
License:    TODO
Source0:    %{name}-%{version}.tar.bz2
Requires:   patchmanager

%description
A patch to send messages using the enter key for the jolla-messages app.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/patchmanager/patches/%{name}
cp -r patch/* %{buildroot}/usr/share/patchmanager/patches/%{name}
mkdir -p %{buildroot}/usr/lib/qt5/qml/org/nickcis/base
cp -r org/* %{buildroot}/usr/lib/qt5/qml/org
# << install pre

# >> install post
# << install post

%pre
# >> pre
if [ -f /usr/sbin/patchmanager ]; then
    /usr/sbin/patchmanager -u %{name} || true
fi
# << pre

%preun
# >> preun
if [ -f /usr/sbin/patchmanager ]; then
    /usr/sbin/patchmanager -u %{name} || true
fi
# << preun

%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/patchmanager/patches/%{name}
%{_libdir}/qt5/qml/org/nickcis/base
# << files
